### ISSUE TITLE
NullPointerException DelegatingAddressPicker.java:69 [hazelcast-3.11.1.jar:3.11.1]

### ISSUE THREAD

**Issue by robinroos** [bitsofinfo/hazelcast-docker-swarm-discovery-spi#25]
Hello,

`Feb 13 10:16:37 CSINTFINSDCKS01 data-service[960]: 2019-02-13 10:16:37.844 INFO [ips-data-service,,,] 1 --- [      main] s.d.s.d.DockerDNSRRMemberAddressProvider : Resolved domain name 'data-service' to address(es): [data-service/10.0.5.112]
Feb 13 10:16:37 CSINTFINSDCKS01 data-service[960]: 2019-02-13 10:16:37.859 ERROR [ips-data-service,,,] 1 --- [      main] com.hazelcast.instance.AddressPicker   : [LOCAL] [test-ips-data-service-session] [3.11.1] null
Feb 13 10:16:37 CSINTFINSDCKS01 data-service[960]: 
Feb 13 10:16:37 CSINTFINSDCKS01 data-service[960]: java.lang.NullPointerException: null
Feb 13 10:16:37 CSINTFINSDCKS01 data-service[960]: #011at com.hazelcast.instance.DelegatingAddressPicker.validatePublicAddress(DelegatingAddressPicker.java:69) ~[hazelcast-3.11.1.jar:3.11.1]`

I just deployed DNSRR for the first time in our Docker Swarm.  Well, Jenkins deployed it for me....

I have seen the above snipped from the log which shows the embedded Hazelcast cache failing to bootstrap.  The log shows that serviceName=data-service has been "resolved" to a set of just one address, 10.0.5.12.  Subsequently, binding fails probably because 10.0.5.12 is not amongst the set of networkInterfaceAddresses identified by DockerDNSRRMemberAddressProvider.

I know this represents very little information to go on, but any ideas would be greatly appreciated.

Of note, I am not passing serviceName, servicePort or peerServicesCsv as variables but have hard coded them as literals in hazelcast.xml:

`<property name="serviceName">data-service</property>
<property name="servicePort">5701</property>
<property name="peerServicesCsv">data-service:5701</property>
`

I will attach the full hazelcast.xml, which is very similar to the minimalist DNSRR example suggested by this project.

Thanks, Robin.

**Comment by robinroos** [comment]
hazelcast.xml:

`<?xml version="1.0" encoding="UTF-8"?>

<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-3.11.xsd">

    <group>
        <name>${cas.env}-ips-data-service-session</name>
        <password>ignored</password>
    </group>
    <management-center enabled="true">http://springboot-hazelcast:8080/hazelcast-mancenter</management-center>
    <network>
        
        <port auto-increment="false">5701</port>
        <member-address-provider enabled="true">
            <class-name>org.bitsofinfo.hazelcast.spi.docker.swarm.dnsrr.DockerDNSRRMemberAddressProvider</class-name>
            <properties>
                
                <property name="serviceName">data-service</property>

                
                <property name="servicePort">5701</property>
            </properties>
        </member-address-provider>
        <outbound-ports>
            
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="false"/>
            <aws enabled="false"/>
            <gcp enabled="false"/>
            <azure enabled="false"/>
            <kubernetes enabled="false"/>
            <eureka enabled="false"/>
            <discovery-strategies>
                <discovery-strategy
                        enabled="true"
                        class="org.bitsofinfo.hazelcast.spi.docker.swarm.dnsrr.discovery.DockerDNSRRDiscoveryStrategy"
                >
                    <properties>
                        
                        <property name="peerServicesCsv">data-service:5701</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
    </network>
</hazelcast>
`

**Comment by robinroos** [comment]
data-service definition:

```
data-service:
    image: “…/ips-data-service:9"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 300s
      update_config:
        parallelism: 2
        delay: 15s
        order: stop-first
        monitor: 20s
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 15s
        order: stop-first
        monitor: 20s
        failure_action: pause
      placement:
        constraints:
          - node.labels.secure==true
    networks:
      - ips_network
      - spring_svc_network
    environment:
      - SPRING_PROFILES_ACTIVE=test
    logging:
      driver: syslog
      options:
        tag: data-service
```
